version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: '10:00'
      timezone: 'America/Toronto'
    commit-message:
      prefix: chore
    assignees:
      - halostatue

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '10:00'
      timezone: 'America/Toronto'
    commit-message:
      prefix: chore
    assignees:
      - halostatue
