name: Check DCO

on:
  pull_request:

jobs:
  check-dco:
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@v1.1
        with:
          exempt-authors: |
            @kineticcommerce.com
            @kineticcafe.com
